spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/bamboo?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

jwt:
  secret-key: iocyuiasfmlfksdciohvb1j23iuoch32iujbj2kbjkbjkk1l
  access-exp: 10000
  refresh-exp: 10000